In [ ]:
#load numpy library
import numpy as np


In [40]:
#trivial examples
matA= np.matrix("1,2,4;2,3,1;-4,1,2")
vector_x= np.matrix("2;2;3")
print(matA.shape)
print(vector_x.shape)

(3, 3)
(3, 1)


In [ ]:
vector_b= np.dot(matA,vector_x)
print(vector_b)

In [ ]:
#a non-singular matrix (unique solution),
A=np.matrix("1,4,2;2,3,5;-1,2,1")
b=np.matrix("7;4;1")
x=np.linalg.solve(A,b)
print("Solution x =\n", x)


In [ ]:
# a singular matrix (infinite solutions or none)
A2=np.matrix("1,2,3;2,4,6;1,1,2")
b2=np.matrix("6;12;5")
x2=np.linalg.pinv(A2)@b2
print("One solution x =\n", x2)
print("Check Ax =\n", A2 @ x2)

In [ ]:
# power of a matrix
C = np.matrix("0,1,1,0;1,0,1,1;1,1,0,1;0,1,1,0")
B= np.linalg.matrix_power(C,3)
print(B)


In [ ]:
# (A+B)^2 != A^2 + B^2 + 2.A.B
A=np.matrix("2,4,6;8,10,12;14,16,18")
print(A.shape)
print(B.shape)
B=np.matrix("1,3,1;1,5,1;1,7,1")
C1= A+B
print(np.linalg.matrix_power(C1,2))
print(A**2+B**2+2*A*B)


In [37]:
#is (AB)^2 != A^2B^2?
import numpy as np
A2=np.matrix("1,2;3,4")
B=np.matrix("2,0;1,2")
X= A2@B
print(np.linalg.matrix_power(X, 2))
print(np.linalg.matrix_power(A, 2)@np.linalg.matrix_power(B, 2))

[[ 56  48]
 [120 104]]
[[4*a**2 + 4*a*b + 4*b*c + 4*b*d 4*a*b + 4*b*d]
 [4*a*c + 4*b*c + 4*c*d + 4*d**2 4*b*c + 4*d**2]]


In [43]:
# using Sympy
import sympy as sp
a, b, c, d = sp.symbols('a b c d')
D = sp.Matrix([[3,0],[0,5]])
print (D)
A = sp.Matrix([[a,b],[c,d]])
display (D * A)

E = sp.Matrix([[0,1],[0,1]])
display (E * A)

display (A @ E)
display (A @ D)


Matrix([[3, 0], [0, 5]])


Matrix([
[3*a, 3*b],
[5*c, 5*d]])

Matrix([
[c, d],
[c, d]])

Matrix([
[0, a + b],
[0, c + d]])

Matrix([
[3*a, 5*b],
[3*c, 5*d]])

In [38]:
# Determinant, Rank and Inverse of a Matrix
Det = np.linalg.det(A2)
Rank = np.linalg.matrix_rank(A2)
Inv = np.linalg.inv(A2)

print("Determinant:", Det)
print("Rank:", Rank)
print("Inverse:\n", Inv)


Determinant: -2.0000000000000004
Rank: 2
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [44]:
#Augmented matrix
aug= np.hstack((matA,vector_x))
print(aug)
print(np.hstack((D,E)))

[[ 1  2  4  2]
 [ 2  3  1  2]
 [-4  1  2  3]]
[[3 0 0 1]
 [0 5 0 1]]


In [53]:
import fractions as Fraction
A3 = np.matrix("2,3;4,7")
A3_inv = np.linalg.inv(A3)
print(np.vectorize(Fraction.Fraction)(A3_inv))

[[Fraction(7, 2) Fraction(-3, 2)]
 [Fraction(-2, 1) Fraction(1, 1)]]


In [ ]:
A4=np.matrix("10,20;20,50")
vector_b=np.matrix("1;0")
# print(np.linalg.inv(A4))
print(np.linalg.solve(A4,vector_b))

sol= np.transpose(vector_b) @ np.linalg.inv(A4)
print(sol)


[[ 0.5]
 [-0.2]]
[[ 0.5 -0.2]]
