In [3]:
#load numpy library
import numpy as np


In [ ]:
#trivial examples
matA= np.matrix("1,2,4;2,3,1;-4,1,2")
vector_x= np.matrix("2;2;3")
print(matA.shape)
print(vector_x.shape)

(3, 3)
(3, 1)


In [15]:
vector_b= np.dot(matA,vector_x)
print(vector_b)

[[18]
 [13]
 [ 0]]


In [ ]:
#a non-singular matrix (unique solution),
A=np.matrix("1,4,2;2,3,5;-1,2,1")
b=np.matrix("7;4;1")
x=np.linalg.solve(A,b)
print("Solution x =\n", x)


Solution x =
 [[ 1.66666667]
 [ 1.80952381]
 [-0.95238095]]


In [23]:
# a singular matrix (infinite solutions or none)
A2=np.matrix("1,2,3;2,4,6;1,1,2")
b2=np.matrix("6;12;5")
x2=np.linalg.pinv(A2)@b2
print("One solution x =\n", x2)
print("Check Ax =\n", A2 @ x2)

One solution x =
 [[ 2.33333333]
 [-0.66666667]
 [ 1.66666667]]
Check Ax =
 [[ 6.]
 [12.]
 [ 5.]]
